name: sqlite3_flutter_libs
description: >-
  Flutter plugin providing custom SQLite build with extensions (FTS5, USearch, SQLean).
  Drop-in replacement for sqlite3_flutter_libs.
version: 0.5.40

homepage: https://github.com/mertalev/SQLiteDataCustom

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: eu.simonbinder.sqlite3_flutter_libs
        pluginClass: Sqlite3FlutterLibsPlugin
      ios:
        pluginClass: Sqlite3FlutterLibsPlugin
        sharedDarwinSource: true
      macos:
        pluginClass: Sqlite3FlutterLibsPlugin
        sharedDarwinSource: true
